// =============================================================
// MIROIR CLIENT DES DEFINITIONS SERVEUR (AFFICHAGE UNIQUEMENT)
// =============================================================
// Ces donnees sont un miroir de server_defs.sql.
// Elles sont utilisees UNIQUEMENT pour l'affichage (couts,
// temps, descriptions, prerequis) dans l'interface.
// Le client N'ENVOIE JAMAIS ces valeurs au serveur.
// Toutes les actions (construction, recherche, etc.) envoient
// seulement les identifiants (buildingId, shipId, etc.).
// Le serveur calcule les couts et durees a partir de ses
// propres tables (*_defs).
//
// IMPORTANT: Si vous modifiez le game design, mettez a jour
// AUSSI server_defs.sql (source de verite) et re-executez-le.
//
// Les routes tRPC defs.getBuildingDefs, defs.getShipDefs, etc.
// permettent de verifier la coherence avec le serveur.
// =============================================================
import { BuildingDef, ResearchDef, ShipDef, DefenseDef, GameState } from '@/types/game';

export const BUILDINGS: BuildingDef[] = [
  {
    id: 'ferMine',
    name: 'Ferro Mine',
    description: 'Extrait le minerai de fer des profondeurs de la planète.',
    category: 'resources',
    baseCost: { fer: 60, silice: 15 },
    costFactor: 1.5,
    baseProduction: { fer: 30 },
    baseTime: 30,
    timeFactor: 1.8,
  },
  {
    id: 'siliceMine',
    name: 'Silica Mine',
    description: 'Récolte les formations de silice cristalline souterraines.',
    category: 'resources',
    baseCost: { fer: 48, silice: 24 },
    costFactor: 1.6,
    baseProduction: { silice: 20 },
    baseTime: 40,
    timeFactor: 1.8,
  },
  {
    id: 'xenogasRefinery',
    name: 'Xeno Well',
    description: 'Synthétise le Xenogas à partir des gaz atmosphériques.',
    category: 'resources',
    baseCost: { fer: 225, silice: 75 },
    costFactor: 1.5,
    baseProduction: { xenogas: 10 },
    baseTime: 60,
    timeFactor: 1.8,
    prerequisites: [{ type: 'building', id: 'ferMine', level: 1 }],
  },
  {
    id: 'solarPlant',
    name: 'Power Plant',
    description: 'Convertit le rayonnement solaire en énergie utilisable.',
    category: 'resources',
    baseCost: { fer: 75, silice: 30 },
    costFactor: 1.5,
    baseProduction: { energy: 20 },
    baseTime: 30,
    timeFactor: 1.8,
  },
  {
    id: 'ferroStore',
    name: 'Ferro Store',
    description: 'Entrepôt sécurisé pour le stockage de fer raffiné.',
    category: 'resources',
    baseCost: { fer: 1000 },
    costFactor: 2,
    baseTime: 40,
    timeFactor: 1.8,
  },
  {
    id: 'silicaStore',
    name: 'Silica Store',
    description: 'Chambre de stockage pressurisée pour la silice cristalline.',
    category: 'resources',
    baseCost: { fer: 1000, silice: 500 },
    costFactor: 2,
    baseTime: 40,
    timeFactor: 1.8,
  },
  {
    id: 'xenoStore',
    name: 'Xeno Store',
    description: 'Réservoir cryogénique pour le stockage de Xenogas.',
    category: 'resources',
    baseCost: { fer: 1000, silice: 1000 },
    costFactor: 2,
    baseTime: 50,
    timeFactor: 1.8,
    prerequisites: [{ type: 'building', id: 'xenogasRefinery', level: 1 }],
  },
  {
    id: 'roboticsFactory',
    name: 'Automata Foundry',
    description: 'Les systèmes automatisés accélèrent toute construction.',
    category: 'facilities',
    baseCost: { fer: 400, silice: 120, xenogas: 200 },
    costFactor: 2,
    baseTime: 120,
    timeFactor: 2,
  },
  {
    id: 'shipyard',
    name: 'Orbital Assembly Dock',
    description: 'Dock orbital pour la construction de vaisseaux et de défenses.',
    category: 'facilities',
    baseCost: { fer: 400, silice: 200, xenogas: 100 },
    costFactor: 2,
    baseTime: 120,
    timeFactor: 2,
    prerequisites: [{ type: 'building', id: 'roboticsFactory', level: 2 }],
  },
  {
    id: 'researchLab',
    name: 'Arcology Research Lab',
    description: 'Installation dédiée à la recherche technologique avancée.',
    category: 'facilities',
    baseCost: { fer: 200, silice: 400, xenogas: 200 },
    costFactor: 2,
    baseTime: 150,
    timeFactor: 2,
  },
  {
    id: 'naniteFactory',
    name: 'Quantum Reactor Core',
    description: 'Assemblage nanométrique pour une construction ultra-rapide.',
    category: 'facilities',
    baseCost: { fer: 1000000, silice: 500000, xenogas: 100000 },
    costFactor: 2,
    baseTime: 3600,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'roboticsFactory', level: 10 },
      { type: 'research', id: 'computerTech', level: 10 },
    ],
  },
  {
    id: 'geoformEngine',
    name: 'Geoform Engine',
    description: 'Terraformation avancée pour étendre les champs disponibles de la planète.',
    category: 'facilities',
    baseCost: { fer: 0, silice: 50000, xenogas: 100000, energy: 1000 },
    costFactor: 2,
    baseTime: 7200,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'naniteFactory', level: 1 },
      { type: 'research', id: 'quantumFlux', level: 12 },
    ],
  },
];

export const RESEARCH: ResearchDef[] = [
  {
    id: 'quantumFlux',
    name: 'Flux Quantique',
    description: 'Optimise l\'énergie, augmente l\'efficacité des centrales et mines.',
    baseCost: { silice: 800, xenogas: 400 },
    costFactor: 2,
    baseTime: 120,
    timeFactor: 2,
    prerequisites: [{ type: 'building', id: 'researchLab', level: 1 }],
  },
  {
    id: 'particleBeam',
    name: 'Rayon à Particules',
    description: 'Débloque les premières armes à faisceau, base de la techno offensive.',
    baseCost: { fer: 200, silice: 100 },
    costFactor: 2,
    baseTime: 90,
    timeFactor: 2,
    prerequisites: [{ type: 'building', id: 'researchLab', level: 1 }],
  },
  {
    id: 'ionicStream',
    name: 'Flux Ionique',
    description: 'Améliore blindages énergétiques et débloque armes ioniques.',
    baseCost: { fer: 1000, silice: 300, xenogas: 100 },
    costFactor: 2,
    baseTime: 150,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 4 },
      { type: 'research', id: 'particleBeam', level: 5 },
      { type: 'research', id: 'quantumFlux', level: 4 },
    ],
  },
  {
    id: 'plasmaOverdrive',
    name: 'Surchauffe Plasmatique',
    description: 'Bonus sur l\'extraction (Ferro, Silica, XenoGas), débloque armes lourdes.',
    baseCost: { fer: 2000, silice: 4000, xenogas: 1000 },
    costFactor: 2,
    baseTime: 300,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 4 },
      { type: 'research', id: 'particleBeam', level: 10 },
      { type: 'research', id: 'ionicStream', level: 5 },
    ],
  },
  {
    id: 'weaponsTech',
    name: 'Systèmes Balistiques',
    description: 'Augmente la puissance de feu de toutes les unités de combat.',
    baseCost: { fer: 800, silice: 200 },
    costFactor: 2,
    baseTime: 150,
    timeFactor: 2,
    prerequisites: [{ type: 'building', id: 'researchLab', level: 4 }],
  },
  {
    id: 'shieldTech',
    name: 'Champs Déflecteurs',
    description: 'Renforce les boucliers énergétiques de toutes les unités.',
    baseCost: { fer: 200, silice: 600 },
    costFactor: 2,
    baseTime: 150,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 6 },
      { type: 'research', id: 'quantumFlux', level: 3 },
    ],
  },
  {
    id: 'armorTech',
    name: 'Alliages Nano-Tressés',
    description: 'Renforce le blindage de coque sur toutes les unités.',
    baseCost: { fer: 1000 },
    costFactor: 2,
    baseTime: 120,
    timeFactor: 2,
    prerequisites: [{ type: 'building', id: 'researchLab', level: 2 }],
  },
  {
    id: 'chemicalDrive',
    name: 'Propulsion Chimique',
    description: 'Propulsion basique pour petits vaisseaux (scouts, cargos légers).',
    baseCost: { fer: 400, silice: 600 },
    costFactor: 2,
    baseTime: 180,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 1 },
      { type: 'research', id: 'quantumFlux', level: 1 },
    ],
  },
  {
    id: 'impulseReactor',
    name: 'Réacteur à Impulsions',
    description: 'Débloque chasseurs + transporteurs moyens, vitesse améliorée.',
    baseCost: { fer: 2000, silice: 4000, xenogas: 600 },
    costFactor: 2,
    baseTime: 300,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 2 },
      { type: 'research', id: 'quantumFlux', level: 1 },
    ],
  },
  {
    id: 'voidDrive',
    name: 'Voile Hyperspatial',
    description: 'Propulsion hyperespace pour les grands vaisseaux et voyages intergalactiques.',
    baseCost: { fer: 10000, silice: 20000, xenogas: 6000 },
    costFactor: 2,
    baseTime: 600,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 7 },
      { type: 'research', id: 'quantumFlux', level: 5 },
      { type: 'research', id: 'impulseReactor', level: 3 },
    ],
  },
  {
    id: 'computerTech',
    name: 'IA Stratégique',
    description: 'Augmente le nombre de flottes pouvant être en mission simultanément.',
    baseCost: { silice: 400, xenogas: 600 },
    costFactor: 2,
    baseTime: 120,
    timeFactor: 2,
    prerequisites: [{ type: 'building', id: 'researchLab', level: 1 }],
  },
  {
    id: 'espionageTech',
    name: 'Sonar Cosmique',
    description: 'Collecte de renseignements sur les planètes ennemies.',
    baseCost: { fer: 200, silice: 1000, xenogas: 200 },
    costFactor: 2,
    baseTime: 120,
    timeFactor: 2,
    prerequisites: [{ type: 'building', id: 'researchLab', level: 3 }],
  },
  {
    id: 'astrophysics',
    name: 'Xéno-Cartographie',
    description: 'Permet la colonisation de nouvelles planètes et l\'exploration galactique.',
    baseCost: { fer: 4000, silice: 8000, xenogas: 4000 },
    costFactor: 1.75,
    baseTime: 600,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 3 },
      { type: 'research', id: 'espionageTech', level: 4 },
      { type: 'research', id: 'impulseReactor', level: 3 },
    ],
  },
  {
    id: 'subspacialNodes',
    name: 'Noeuds Subspatiaux',
    description: 'Augmente la capacité de fret des vaisseaux et booste l\'hyperpropulsion.',
    baseCost: { fer: 0, silice: 4000, xenogas: 2000 },
    costFactor: 2,
    baseTime: 300,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 7 },
      { type: 'research', id: 'quantumFlux', level: 5 },
      { type: 'research', id: 'voidDrive', level: 3 },
    ],
  },
  {
    id: 'neuralMesh',
    name: 'Maillage Neuronal',
    description: 'Permet de combiner le niveau des laboratoires entre les planètes pour accélérer la recherche.',
    baseCost: { fer: 240000, silice: 400000, xenogas: 160000 },
    costFactor: 2,
    baseTime: 600,
    timeFactor: 2,
    prerequisites: [
      { type: 'building', id: 'researchLab', level: 10 },
      { type: 'research', id: 'computerTech', level: 8 },
      { type: 'research', id: 'voidDrive', level: 8 },
    ],
  },
  {
    id: 'gravitonTech',
    name: 'Manipulation Gravitationnelle',
    description: 'Débloque le Titan Astral, l\'arme ultime de destruction massive.',
    baseCost: { energy: 300000 },
    costFactor: 3,
    baseTime: 3600,
    timeFactor: 3,
    prerequisites: [{ type: 'building', id: 'researchLab', level: 12 }],
  },
];

export const SHIPS: ShipDef[] = [
  {
    id: 'novaScout',
    name: 'Nova Scout',
    description: 'Intercepteur de combat rapide et agile.',
    cost: { fer: 3000, silice: 1000 },
    buildTime: 30,
    baseFuelCost: 20,
    stats: { attack: 50, shield: 10, hull: 400, speed: 12500, cargo: 50 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 1 },
      { type: 'research', id: 'chemicalDrive', level: 1 },
    ],
  },
  {
    id: 'ferDeLance',
    name: 'Fer de Lance',
    description: 'Chasseur d\'assaut blindé avec armement lourd.',
    cost: { fer: 6000, silice: 4000 },
    buildTime: 60,
    baseFuelCost: 40,
    stats: { attack: 150, shield: 25, hull: 1000, speed: 10000, cargo: 100 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 3 },
      { type: 'research', id: 'armorTech', level: 2 },
      { type: 'research', id: 'impulseReactor', level: 2 },
    ],
  },
  {
    id: 'cyclone',
    name: 'Cyclone',
    description: 'Vaisseau de guerre polyvalent pour les opérations de flotte.',
    cost: { fer: 20000, silice: 7000, xenogas: 2000 },
    buildTime: 120,
    baseFuelCost: 75,
    stats: { attack: 400, shield: 50, hull: 2700, speed: 15000, cargo: 800 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 5 },
      { type: 'research', id: 'impulseReactor', level: 4 },
      { type: 'research', id: 'ionicStream', level: 2 },
    ],
  },
  {
    id: 'bastion',
    name: 'Bastion',
    description: 'Vaisseau capital avec une puissance de feu dévastatrice.',
    cost: { fer: 45000, silice: 15000 },
    buildTime: 180,
    baseFuelCost: 500,
    stats: { attack: 1000, shield: 200, hull: 6000, speed: 10000, cargo: 1500 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 7 },
      { type: 'research', id: 'voidDrive', level: 4 },
    ],
  },
  {
    id: 'pyro',
    name: 'Pyro',
    description: 'Bombardier lourd spécialisé dans la destruction des défenses planétaires.',
    cost: { fer: 50000, silice: 25000, xenogas: 15000 },
    buildTime: 240,
    baseFuelCost: 1000,
    stats: { attack: 1000, shield: 500, hull: 7500, speed: 4000, cargo: 500 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 8 },
      { type: 'research', id: 'impulseReactor', level: 6 },
      { type: 'research', id: 'plasmaOverdrive', level: 5 },
    ],
  },
  {
    id: 'nemesis',
    name: 'Nemesis',
    description: 'Croiseur de bataille anti-chasseurs avec une vitesse supérieure.',
    cost: { fer: 30000, silice: 40000, xenogas: 15000 },
    buildTime: 180,
    baseFuelCost: 800,
    stats: { attack: 700, shield: 400, hull: 7000, speed: 10000, cargo: 750 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 8 },
      { type: 'research', id: 'voidDrive', level: 5 },
      { type: 'research', id: 'particleBeam', level: 12 },
    ],
  },
  {
    id: 'fulgurant',
    name: 'Fulgurant',
    description: 'Destroyer massif capable de percer n\'importe quel blindage.',
    cost: { fer: 60000, silice: 50000, xenogas: 15000 },
    buildTime: 300,
    baseFuelCost: 1000,
    stats: { attack: 2000, shield: 500, hull: 11000, speed: 5000, cargo: 2000 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 9 },
      { type: 'research', id: 'voidDrive', level: 6 },
      { type: 'research', id: 'ionicStream', level: 5 },
    ],
  },
  {
    id: 'titanAstral',
    name: 'Titan Astral',
    description: 'Arme ultime de destruction stellaire. Peut anéantir une lune entière.',
    cost: { fer: 5000000, silice: 4000000, xenogas: 1000000 },
    buildTime: 3600,
    baseFuelCost: 100000,
    stats: { attack: 200000, shield: 50000, hull: 900000, speed: 100, cargo: 1000000 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 12 },
      { type: 'research', id: 'voidDrive', level: 7 },
      { type: 'research', id: 'gravitonTech', level: 1 },
    ],
  },
  {
    id: 'atlasCargo',
    name: 'Atlas Cargo',
    description: 'Transport léger pour le convoyage de ressources.',
    cost: { fer: 2000, silice: 2000 },
    buildTime: 20,
    baseFuelCost: 20,
    stats: { attack: 5, shield: 10, hull: 400, speed: 10000, cargo: 5000 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 2 },
      { type: 'research', id: 'chemicalDrive', level: 2 },
    ],
  },
  {
    id: 'atlasCargoXL',
    name: 'Atlas Cargo XL',
    description: 'Cargo lourd pour des opérations de transport massives.',
    cost: { fer: 6000, silice: 6000 },
    buildTime: 40,
    baseFuelCost: 50,
    stats: { attack: 5, shield: 25, hull: 1200, speed: 7500, cargo: 25000 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 4 },
      { type: 'research', id: 'chemicalDrive', level: 6 },
    ],
  },
  {
    id: 'colonyShip',
    name: 'Barge Coloniale',
    description: 'Établit de nouvelles colonies sur des mondes inhabités.',
    cost: { fer: 10000, silice: 20000, xenogas: 10000 },
    buildTime: 300,
    baseFuelCost: 1000,
    stats: { attack: 50, shield: 100, hull: 3000, speed: 2500, cargo: 7500 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 4 },
      { type: 'research', id: 'impulseReactor', level: 3 },
      { type: 'research', id: 'astrophysics', level: 1 },
    ],
  },
  {
    id: 'mantaRecup',
    name: 'Manta Recup',
    description: 'Récupère les débris flottants après une bataille spatiale.',
    cost: { fer: 10000, silice: 6000, xenogas: 2000 },
    buildTime: 60,
    baseFuelCost: 300,
    stats: { attack: 1, shield: 10, hull: 1600, speed: 2000, cargo: 20000 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 4 },
      { type: 'research', id: 'chemicalDrive', level: 6 },
      { type: 'research', id: 'shieldTech', level: 2 },
    ],
  },
  {
    id: 'spectreSonde',
    name: 'Spectre Sonde',
    description: 'Drone furtif pour la collecte de renseignements ennemis.',
    cost: { silice: 1000 },
    buildTime: 10,
    baseFuelCost: 1,
    stats: { attack: 0, shield: 0, hull: 100, speed: 100000000, cargo: 0 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 3 },
      { type: 'research', id: 'chemicalDrive', level: 3 },
      { type: 'research', id: 'espionageTech', level: 2 },
    ],
  },
  {
    id: 'heliosRemorqueur',
    name: 'Helios Remorqueur',
    description: 'Satellite solaire qui produit de l\'énergie en orbite.',
    cost: { silice: 2000, xenogas: 500 },
    buildTime: 10,
    baseFuelCost: 0,
    stats: { attack: 1, shield: 1, hull: 200, speed: 0, cargo: 0 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 1 },
    ],
  },
];

export const DEFENSES: DefenseDef[] = [
  {
    id: 'kineticTurret',
    name: 'Tourelle Cinétique',
    description: 'Système simple et fiable qui lance des salves de projectiles métalliques à haute vitesse.',
    cost: { fer: 2000 },
    buildTime: 15,
    stats: { attack: 80, shield: 20, hull: 200 },
    prerequisites: [{ type: 'building', id: 'shipyard', level: 1 }],
  },
  {
    id: 'pulseCannon',
    name: 'Canon à Impulsion',
    description: 'Émet des rafales d\'énergie concentrée. Tir rapide et précis contre les petites unités.',
    cost: { fer: 1500, silice: 500 },
    buildTime: 20,
    stats: { attack: 100, shield: 25, hull: 250 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 2 },
      { type: 'research', id: 'quantumFlux', level: 2 },
      { type: 'research', id: 'particleBeam', level: 3 },
    ],
  },
  {
    id: 'beamCannon',
    name: 'Canon de Faisceau',
    description: 'Version avancée du canon à impulsion avec un faisceau continu capable de percer les blindages moyens.',
    cost: { fer: 6000, silice: 2000 },
    buildTime: 30,
    stats: { attack: 250, shield: 100, hull: 800 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 4 },
      { type: 'research', id: 'quantumFlux', level: 3 },
      { type: 'research', id: 'particleBeam', level: 6 },
    ],
  },
  {
    id: 'massDriver',
    name: 'Canon de Masse',
    description: 'Arme lourde lançant des obus hyper-denses. Dévastateur contre les vaisseaux lourds.',
    cost: { fer: 20000, silice: 15000, xenogas: 2000 },
    buildTime: 60,
    stats: { attack: 1100, shield: 200, hull: 3500 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 6 },
      { type: 'research', id: 'weaponsTech', level: 3 },
      { type: 'research', id: 'quantumFlux', level: 6 },
      { type: 'research', id: 'shieldTech', level: 1 },
    ],
  },
  {
    id: 'ionProjector',
    name: 'Projecteur Ionique',
    description: 'Génère une décharge ionisée qui perturbe l\'électronique ennemie et affaiblit les boucliers.',
    cost: { fer: 5000, silice: 3000 },
    buildTime: 30,
    stats: { attack: 150, shield: 500, hull: 800 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 4 },
      { type: 'research', id: 'ionicStream', level: 4 },
    ],
  },
  {
    id: 'solarCannon',
    name: 'Canon Solaire',
    description: 'Redirige l\'énergie d\'un mini-réacteur stellaire pour lancer du plasma surchauffé.',
    cost: { fer: 50000, silice: 50000, xenogas: 30000 },
    buildTime: 120,
    stats: { attack: 3000, shield: 300, hull: 10000 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 8 },
      { type: 'research', id: 'plasmaOverdrive', level: 7 },
    ],
  },
  {
    id: 'smallShield',
    name: 'Petit Bouclier Planétaire',
    description: 'Dôme de protection énergétique couvrant une zone restreinte de la planète.',
    cost: { fer: 10000, silice: 10000 },
    buildTime: 120,
    stats: { attack: 1, shield: 2000, hull: 2000 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 1 },
      { type: 'research', id: 'shieldTech', level: 2 },
    ],
  },
  {
    id: 'largeShield',
    name: 'Grand Bouclier Planétaire',
    description: 'Bouclier énergétique massif protégeant l\'ensemble de la planète.',
    cost: { fer: 50000, silice: 50000 },
    buildTime: 300,
    stats: { attack: 1, shield: 10000, hull: 10000 },
    prerequisites: [
      { type: 'building', id: 'shipyard', level: 6 },
      { type: 'research', id: 'shieldTech', level: 6 },
    ],
  },
];

export const DEFAULT_STATE: GameState = {
  planetName: 'Homeworld',
  coordinates: [1, 42, 5],
  buildings: {},
  research: {},
  ships: {},
  defenses: {},
  resources: {
    fer: 50000,
    silice: 25000,
    xenogas: 10000,
    energy: 0,
  },
  solar: 500,
  lastUpdate: Date.now(),
  activeTimers: [],
  shipyardQueue: [],
  _resetVersion: 2,
};
